contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - alpine-baselayout-data
    - alpine-release
    - busybox
    - ca-certificates-bundle
    - gcc
    - go
    - musl-dev
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  # TODO: this should run as 65532
  run-as: 0
entrypoint:
  command: /usr/bin/go
cmd: help
