name: PreSubmit-Build

on:
  pull_request:

jobs:
  build:
    name: Build hello-world OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
      shell: bash


    - uses: sigstore/cosign-installer@main
    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        archs: x86_64,aarch64,armv7

    - uses: distroless/actions/apko-build@main
      with:
        config: apko.yaml
        tag: hello-world:${{ steps.snapshot-date.outputs.date }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64,armv7
        source-date-epoch: ${{ steps.snapshot-date.outputs.epoch }}

    - uses: actions/upload-artifact@v3
      with:
        name: hello-world.tar
        path: ./output.tar
