contents:
  packages:
    - php

entrypoint:
  command: /bin/php

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

paths:
  - path: /app
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

work-dir: /app

accounts:
  groups:
    - groupname: php
      gid: 65532
  users:
    - username: php
      uid: 65532
      gid: 65532
  run-as: 65532

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/php/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/php
