contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - wolfi-baselayout
    - busybox
    - php
    - composer

entrypoint:
  command: /bin/php

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

paths:
  - path: /app
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

work-dir: /app

accounts:
  groups:
    - groupname: php
      gid: 65532
  users:
    - username: php
      uid: 65532
      gid: 65532

archs:
  - x86_64
