contents:
  # fluent-bit comes in via var.extra_packages
  packages:
    - libpq-11

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 0

paths:
  - path: /var/lib/fluent-bit
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

entrypoint:
  command: /usr/bin/fluent-bit

cmd: --config=/fluent-bit/etc/fluent-bit.conf
