contents:
    packages:
      - openjdk-11-jre
      - openjdk-11-default-jvm
      - wavefront-proxy
      - wavefront-proxy-config
      - wavefront-proxy-licenses
      - wavefront-proxy-oci-entrypoint
      - bash
      - busybox

accounts:
  groups:
    - groupname: wavefront
      gid: 65532
  users:
    - username: wavefront
      uid: 65532
      gid: 65532
  run-as: 65532


paths:
  - path: /var/spool/wavefront-proxy
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o777
    recursive: true
  - path: /var/log/wavefront
    uid: 65532
    gid: 65532
    type: directory
    permissions: 0o777
    recursive: true

entrypoint:
  command: /usr/local/bin/run.sh

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/wavefront-proxy/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/wavefront-proxy