contents:
  packages:
    - ca-certificates-bundle
    - su-exec
    - envoy
    - envoy-oci-entrypoint
    - envoy-config

accounts:
  groups:
    - groupname: envoy
      gid: 65532
  users:
    - username: envoy
      uid: 65532
  run-as: envoy
  recursive: true

entrypoint:
  command: /var/lib/envoy/init/envoy-entrypoint.sh

paths:
  - path: /etc/envoy
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/envoy/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/envoy
