contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - su-exec
    - envoy
    - envoy-oci-entrypoint
    - envoy-config

accounts:
  groups:
    - groupname: envoy
      gid: 65532
  users:
    - username: envoy
      uid: 65532
  run-as: envoy
  recursive: true

entrypoint:
  command: /var/lib/envoy/init/envoy-entrypoint.sh

paths:
  - path: /etc/envoy
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

archs:
  - x86_64
  - aarch64
