contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - nginx
    - nginx-package-config
accounts:
  groups:
    - groupname: nginx
      gid: 65532
  users:
    - username: nginx
      uid: 65532
      gid: 65532
  run-as: 65532
paths:
  - path: /var/lib/nginx
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755
    recursive: true
  - path: /var/lib/nginx/tmp
    uid: 65532
    gid: 65532
    type: directory
    permissions: 0o755
    recursive: true
  - path: /var/run
    uid: 65532
    gid: 65532
    type: directory
    permissions: 0o755
    recursive: false
entrypoint:
  command: /usr/sbin/nginx
cmd: -c /etc/nginx/nginx.conf -g "daemon off;"
stop-signal: SIGQUIT
archs:
  - x86_64
  - aarch64
environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
