contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - cluster-autoscaler
    - wolfi-baselayout
    - ca-certificates-bundle
accounts:
  groups:
    - groupname: cluster-autoscaler
      gid: 65532
  users:
    - username: cluster-autoscaler
      uid: 65532
  run-as: 65532
entrypoint:
  command: /usr/bin/cluster-autoscaler
archs:
  - x86_64
  - aarch64
environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
