contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - weaviate
    - openssl

paths:
  - path: /modules
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

entrypoint:
  command: /usr/bin/weaviate
cmd: --host 0.0.0.0 --port 8080 --scheme http

accounts:
  groups:
    - groupname: weaviate
      gid: 65532
  users:
    - username: weaviate
      uid: 65532
  run-as: 65532

archs:
- x86_64
- aarch64
