contents:
  packages:
    - busybox
    - opensearch-2
    - openjdk-11-default-jvm

accounts:
  groups:
    - groupname: opensearch
      gid: 65532
  users:
    - username: opensearch
      uid: 65532
  run-as: opensearch
  recursive: true

environment:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk

entrypoint:
  command: /usr/bin/docker-entrypoint.sh
cmd: opensearchwrapper

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/opensearch/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/opensearch
