contents:
  packages:
    - mc
    - bash

accounts:
  groups:
    - groupname: minio
      gid: 65532
  users:
    - username: minio
      uid: 65532
  run-as: minio
  recursive: true

entrypoint:
  command: /usr/bin/mc

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/mc/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/mc
