contents:
  packages:
    - skaffold
    - google-cloud-sdk
    - helm
    - kustomize
    - kpt

paths:
  - path: /app
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

work-dir: /app

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin

entrypoint:
  command: /usr/bin/skaffold
cmd: --help

accounts:
  groups:
    - groupname: skaffold
      gid: 65532
  users:
    - username: skaffold
      uid: 65532
  run-as: 65532

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/skaffold/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/skaffold
