contents:
  packages:
    - busybox
    - bash
    - tini
    - libatasmart
    - boost-filesystem
    - iproute2

accounts:
  groups:
    - groupname: cassandra
      gid: 999
  users:
    - username: cassandra
      uid: 999
  run-as: 999

work-dir: /

entrypoint:
  command:  "/sbin/tini -g -- /docker-entrypoint.sh"

cmd: mgmtapi

environment:
  LANG: en_US.UTF-8
  CASSANDRA_HOME: /opt/cassandra
  PATH: /usr/sbin:/sbin:/usr/bin:/bin:/opt/cassandra/bin/
  MGMT_API_LOG_DIR: /var/log/cassandra
  CASSANDRA_LOGS_DIR: /opt/cassandra/logs
  CASSANDRA_CONF: /opt/cassandra/conf
  MAAC_PATH: /opt/management-api
  MCAC_PATH: /opt/metrics-collector

paths:
  - path: /var/lib/cassandra
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
  - path: /opt/cassandra
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
  - path: /opt/cassandra/logs
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
  - path: /opt/cassandra/conf
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
  - path: /var/lib/cassandra
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
  - path: /var/log/cassandra
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
  - path: /opt/management-api
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
  - path: /opt/metrics-collector
    type: directory
    permissions: 0o777
    uid: 999
    gid: 999
    recursive: true
