contents:
  packages:
    - pulumi
    - pulumi-watch
    - busybox # Needed for language support

    # for Pulumi Go support
    - pulumi-language-go
    - go

    # for Pulumi Dotnet support
    - pulumi-language-dotnet
    - dotnet-7
    - dotnet-7-runtime
    - dotnet-7-sdk
    - aspnet-7-runtime
    - aspnet-7-targeting-pack

    # for Pulumi Python support
    - pulumi-language-python
    - python-3.11
    - py3.11-pip
    - python-3.11-dev

    # for Pulumi Node.js support
    - pulumi-language-nodejs
    - nodejs
    - nghttp2

    # for Pulumi Java support
    - pulumi-language-java
    - glibc-locale-en
    - openjdk-17-jre
    - openjdk-17
    - libstdc++
    - maven

    # for Pulumi YAML support
    - pulumi-language-yaml

    # other miscellaneous
    - git
    - bash
    - openssh
    - openssh-keyscan

accounts:
  groups:
    - groupname: pulumi
      gid: 65532
  users:
    - username: pulumi
      uid: 65532
  run-as: 0

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  XDG_CONFIG_HOME: /tmp/.config
  XDG_CACHE_HOME: /tmp/.cache
  XDG_CONFIG_CACHE: /tmp/.cache
  LANG: C.UTF-8

entrypoint:
  command: /usr/bin/pulumi
cmd: -h

paths:
  - path: /home/pulumi-kubernetes-operator/.ssh
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o777

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/pulumi
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/pulumi
