contents:
  packages:
    - hugo-extended

entrypoint:
  command: /usr/bin/hugo

work-dir: /hugo

paths:
  - path: /hugo
    type: directory
    permissions: 0o775
    uid: 65532
    gid: 65532

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/hugo/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/hugo
