contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - busybox
    - ca-certificates-bundle
    - dotnet-7-sdk
    - aspnet-7-runtime
    - aspnet-7-targeting-pack
    - wolfi-baselayout

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: nonroot
  recursive: true

archs:
  - x86_64
  - aarch64

cmd: /bin/sh -l

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
