name: prometheus
image: cgr.dev/chainguard/prometheus
logo: https://storage.googleapis.com/chainguard-academy/logos/prometheus.svg
endoflife: ""
console_summary: ""
short_description: Minimal Prometheus Image
compatibility_notes: ""
readme_file: README.md
upstream_url: https://prometheus.io/
keywords:
  - analytics
  - application
  - featured
tier: APPLICATION
aliases:
  - bitnami/prometheus:latest
  - prom/prometheus:latest
