contents:
  packages:
    - aws-for-fluent-bit
    - aws-for-fluent-bit-compat

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532

paths:
  - path: /var/lib/fluent-bit
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

entrypoint:
  command: /fluent-bit/bin/fluent-bit
cmd: -e /fluent-bit/firehose.so -e /fluent-bit/cloudwatch.so -e /fluent-bit/kinesis.so -c /fluent-bit/etc/fluent-bit.conf

annotations:
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/aws-for-fluent-bit/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/aws-for-fluent-bit
