contents:
  packages:
    - busybox
    - powershell

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: root
  recursive: true

entrypoint:
  command: /usr/bin/pwsh

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/powershell/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/powershell
