contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - memcached

accounts:
  groups:
    - groupname: memcached
      gid: 65532
  users:
    - username: memcached
      uid: 65532
  run-as: memcached

entrypoint:
  command: memcached

archs:
- x86_64
- aarch64
