contents:
  packages:
    - prometheus-alertmanager
    - wolfi-base
    - ca-certificates-bundle
    - busybox
paths:
  - path: /alertmanager
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
accounts:
  groups:
    - groupname: alertmanager
      gid: 65532
  users:
    - username: alertmanager
      uid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/alertmanager
cmd: --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/prometheus-alertmanager/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/prometheus-alertmanager
