contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - prometheus-alertmanager
    - wolfi-base
    - ca-certificates-bundle
    - busybox
    - wolfi-baselayout

paths:
  - path: /alertmanager
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532

accounts:
  groups:
    - groupname: alertmanager
      gid: 65532
  users:
    - username: alertmanager
      uid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/alertmanager

cmd: --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/alertmanager

archs:
  - x86_64
  - aarch64

environment:
  PATH: /usr/sbin:/sbin:/usr/bin:/bin
