contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - glibc
    - wolfi-baselayout
    - ca-certificates-bundle
    - ruby3.2-fluentd15

entrypoint:
  type: service-bundle
  services:
    fluentd: /usr/bin/fluentd

environment:
  FLUENTD_CONF: "fluent.conf"
  LD_PRELOAD: ""

accounts:
  groups:
    - groupname: fluent
      gid: 65532
  users:
    - username: fluent
      uid: 65532
      gid: 65532
  run-as: fluent

paths:
  - path: /fluentd/log
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

  - path: /fluentd/etc
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

  - path: /fluentd/plugins
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

    # Set the fluent.conf to an empty file so the image doesn't fail when
    # no options are supplied
  - path: /etc/fluent/fluent.conf
    type: empty-file
    uid: 65532
    gid: 65532
    permissions: 0o644

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/fluentd
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/fluentd
