contents:
  packages:
    - thanos

accounts:
  groups:
    - groupname: thanos
      gid: 65532
  users:
    - username: thanos
      uid: 65532
  run-as: thanos

entrypoint:
  command: thanos

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/thanos/ #use the academy site here
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/thanos #use github here