contents:
  packages:
    - apk-tools
    - busybox
    - bash
    # gcloud comes via var.extra_packages

accounts:
  groups:
    - groupname: gcloud
      gid: 65532
  users:
    - username: gcloud
      uid: 65532
  run-as: 65532
  recursive: true

cmd: /usr/bin/gcloud

