contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - karpenter

accounts:
  groups:
    - groupname: karpenter
      gid: 65532
  users:
    - username: karpenter
      uid: 65532
  run-as: karpenter
  recursive: true

entrypoint:
  command: /usr/bin/controller

archs:
  - x86_64
  - aarch64

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/karpenter/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/karpenter

environment:
  PATH: /usr/sbin:/usr/bin:/bin
