name: prometheus-logstash-exporter
image: cgr.dev/chainguard/prometheus-logstash-exporter
logo: https://storage.googleapis.com/chainguard-academy/logos/prometheus-logstash-exporter.svg
endoflife: ""
console_summary: ""
short_description: Prometheus exporter for Logstash written in Go
compatibility_notes: ""
readme_file: README.md
upstream_url: https://github.com/wolfi-dev/os
keywords:
  - application
