contents:
  packages:
    - k8s-sidecar
    - busybox

environment:
  PYTHONUNBUFFERED: 1

entrypoint:
  command: /usr/share/app/.venv/bin/python -u /usr/share/app/sidecar.py

accounts:
  groups:
    - groupname: k8s-sidecar
      gid: 65532
  users:
    - username: k8s-sidecar
      uid: 65532
  run-as: k8s-sidecar
  recursive: true

annotations:
  "org.opencontainers.image.authors": "Chainguard Team https://www.chainguard.dev/"
  "org.opencontainers.image.url": https://edu.chainguard.dev/chainguard/chainguard-images/reference/k8s-sidecar/
  "org.opencontainers.image.source": https://github.com/chainguard-images/images/tree/main/images/k8s-sidecar
