contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
  packages:
    - ca-certificates-bundle
    - alpine-baselayout-data
    - python3
    - py3-pip
accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

os-release:
  name: Alpine Linux
  id: alpine
  version-id: 3.17
  pretty-name: Alpine Linux 3.17
  home-url: https://alpinelinux.org/
  bug-report-url: https://gitlab.alpinelinux.org/alpine/aports/-/issues
