contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - wolfi-baselayout
    - glibc-locale-en
    - busybox
    - postgresql-15
    - postgresql-15-client
    - postgresql-15-oci-entrypoint
    - postgresql-15-contrib
    - libpq-15
    - su-exec

accounts:
  groups:
    - groupname: postgres
      gid: 70
  users:
    - username: postgres
      uid: 70
  run-as: root

entrypoint:
  command: /var/lib/postgres/initdb/postgresql-entrypoint.sh postgres

environment:
  PGDATA: /var/lib/postgresql/data
  # Postgres defers to locale and docker-library/postgres sets UTF-8 as default.
  LANG: en_US.UTF-8
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

work-dir: /home/postgres

paths:
  - path: /var/lib/postgresql/data
    type: directory
    uid: 70
    gid: 70
    permissions: 0o777

archs:
  - x86_64
  - aarch64
