contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - ca-certificates-bundle
    - glibc-locale-en
    - busybox
    - gradle-8
    - wolfi-baselayout
    - openjdk-17
    - openjdk-17-default-jvm

accounts:
  groups:
    - groupname: gradle
      gid: 65532
  users:
    - username: gradle
      uid: 65532
  run-as: gradle
  recursive: true

work-dir: /home/build

entrypoint:
  command: /usr/bin/gradle

environment:
  LANG: en_US.UTF-8
  JAVA_HOME: /usr/lib/jvm/java-17-openjdk

paths:
  - path: /home/build
    type: directory
    uid: 65532
    gid: 65532
    permissions: 0o755

archs:
  - x86_64
  - aarch64
