contents:
  packages:

accounts:
  groups:
    - groupname: squid
      gid: 65532
  users:
    - username: squid
      uid: 65532
      gid: 65532
  run-as: 65532

paths:
  - path: /var/log/squid
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
    recursive: true
  - path: /var/run
    type: directory
    permissions: 0o777
    uid: 65532
    gid: 65532
    recursive: true

entrypoint:
  command: "/usr/bin/entrypoint.sh"