name: helm
image: cgr.dev/chainguard/helm
logo: https://storage.googleapis.com/chainguard-academy/logos/helm.svg
endoflife: ""
console_summary: ""
short_description: Minimal image with [helm](https://helm.sh) binary.
compatibility_notes: ""
readme_file: README.md
upstream_url: https://github.com/helm/helm
keywords:
  - application
  - kubernetes
tier: APPLICATION
aliases:
  - alpine/helm:latest
  - quay.io/coreos/helm:latest
