name: helm
image: cgr.dev/chainguard/helm
endoflife: ""
console_summary: ""
short_description: Minimal image with [helm](https://helm.sh) binary.
compatibility_notes: ""
readme_file: README.md
upstream_url: https://github.com/helm/helm
keywords:
  - application
tier: APPLICATION
aliases:
  - alpine/helm:latest
  - quay.io/coreos/helm:latest

# resource requests for v2 image builds
resources:
  cpu: 12
  memory: 8Gi
  storage: 6Gi

deployment:
  # no supported charts found
