on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

  # Allow manually triggered workflows by maintainers without any
  # parameters to trigger a proactive rebuild (e.g. when a new
  # apko lands)
  workflow_dispatch: {}

name: Create Release

# Don't run multiple releases concurrently.
concurrency: release

jobs:
  build:
    name: Release OCI image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nginx-version: [1.20.2, 1.23.0]
        include:
          - nginx-version: 1.20.2
            sha256: 958876757782190a1653e14dc26dfc7ba263de310e04c113e11e97d1bef45a42
          - nginx-version: 1.23.0
            sha256: 820acaa35b9272be9e9e72f6defa4a5f2921824709f8aa4772c78ab31ed94cd1

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: sigstore/cosign-installer@main

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0

    - uses: chainguard-dev/actions/melange-build@main
      with:
        sign-with-temporary-key: true
        config: melange.yaml
        empty-workspace: true
        archs: x86_64,aarch64,armv7
        template: "{\"Version\": \"${{ matrix.nginx-version }}\", \"SHA\": \"${{ matrix.sha256 }}\"}"


    - uses: distroless/actions/apko-snapshot@main
      with:
        config: apko.yaml
        base-tag: ghcr.io/${{ github.repository }}
        keyring-append: /github/workspace/melange.rsa.pub
        archs: x86_64,aarch64,armv7
        additional-tags: ${{ matrix.nginx-version }}

    - name: Smoke Test
      run: |
        IMAGE_NAME=$(docker load < output.tar | grep "Loaded image" | sed 's/^Loaded image: //')
        IMAGE_NAME=$IMAGE_NAME ./test.sh

    - if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_ICON: http://github.com/chainguardian.png?size=48
        SLACK_USERNAME: chainguardian
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: distroless
        SLACK_COLOR: '#8E1600'
        MSG_MINIMAL: 'true'
        SLACK_TITLE: Releasing ${{ github.repository }} failed.
        SLACK_MESSAGE: |
          For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    - if: ${{ failure() }}
      name: Setup debug upterm session
      uses: lhotari/action-upterm@v1
