# This build only runs if you add the "melange" label to a PR
on:
  pull_request:
    branches:
      - main
    types: [labeled]
jobs:
  presubmit-matrix-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
    - id: files
      uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42 # v1
      with:
        format: csv
    - id: generate-matrix
      uses: ./.github/actions/generate-matrix
      with:
        modified-files: ${{ steps.files.outputs.all }}
        melange-mode: only
  presubmit-build-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    needs: presubmit-matrix-melange
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix-melange.outputs.matrix) }}
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: ./.github/actions/build-image
        with: ${{ matrix }}
  presubmit-roundup-melange:
    runs-on: ubuntu-latest
    needs: presubmit-build-melange
    steps:
      - run: |
          echo "all matrix jobs completed"
