# This build only runs if you add the "melange" label to a PR
on:
  pull_request:
    branches:
      - main
    types:
      - labeled
jobs:
  presubmit-matrix-melange:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    outputs:
      shard-0: ${{ steps.generate-matrix-0.outputs.matrix }}
      shard-1: ${{ steps.generate-matrix-0.outputs.matrix }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - id: files
        uses: tj-actions/changed-files@9ecc6e7fe2e26945b52485ccd9bc4b44000f5af1 # v36.0.14
        with:
          separator: ','
      - id: generate-matrix-0
        uses: ./.github/actions/generate-matrix
        with:
          shard: 0
          sharding-factor: 2
          modified-files: ${{ steps.files.outputs.all_changed_files }}
          melange-mode: only
      - id: generate-matrix-1
        uses: ./.github/actions/generate-matrix
        with:
          shard: 1
          sharding-factor: 2
          modified-files: ${{ steps.files.outputs.all_changed_files }}
          melange-mode: only

  presubmit-build-melange-0:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    needs: presubmit-matrix-melange
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix-melange.outputs.shard-0) }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Add additional inputs
        id: augmented-inputs
        uses: chainguard-dev/actions/matrix-extra-inputs@main
        with:
          matrix-json: ${{ toJSON(matrix) }}
        env:
          EXTRA_INPUT_APKO_IMAGE: ghcr.io/wolfi-dev/apko:latest@sha256:6d6afe067475323f9d6ce4fc3f9ce9652f9afd5b73ed5cc2b18195086067540c
      - uses: ./.github/actions/build-image
        with: ${{ fromJSON(steps.augmented-inputs.outputs.matrix-json) }}

  presubmit-build-melange-1:
    if: contains(github.event.pull_request.labels.*.name, 'melange')
    runs-on: ubuntu-latest
    needs: presubmit-matrix-melange
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.presubmit-matrix-melange.outputs.shard-1) }}
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Add additional inputs
        id: augmented-inputs
        uses: chainguard-dev/actions/matrix-extra-inputs@main
        with:
          matrix-json: ${{ toJSON(matrix) }}
        env:
          EXTRA_INPUT_APKO_IMAGE: ghcr.io/wolfi-dev/apko:latest@sha256:6d6afe067475323f9d6ce4fc3f9ce9652f9afd5b73ed5cc2b18195086067540c
      - uses: ./.github/actions/build-image
        with: ${{ fromJSON(steps.augmented-inputs.outputs.matrix-json) }}

  presubmit-roundup-melange:
    needs:
      - presubmit-build-melange-0
      - presubmit-build-melange-1
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@45ce8e0eb155657ab8ccf346ade734257fd196a5 # v3.0.3

      - if: ${{ env.WORKFLOW_CONCLUSION == 'success' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 0

      - if: ${{ env.WORKFLOW_CONCLUSION == 'failure' }}
        working-directory: /tmp
        run: echo ${{ env.WORKFLOW_CONCLUSION }} && exit 1
